version: '3.8'
services:
  app:
    build: ./
    depends_on:
      - redis
    environment:
      APP_REDIS_HOST: redis
      APP_REDIS_PORT: 6379
      APP_HTTP_PORT: 5010
      APP_GRPC_PORT: 5000
    ports:
      - "5000:5000"
      - "5010:5010"

  grpcox:
    image: gusaul/grpcox
    ports:
      - 6969:6969

  redis:
    image: redis:alpine

