version: '3'
services:
  redis-cache:
    image: "redis:alpine"
    ports:
      - 6379:6379
  
  fibonacci:
    # build: ./
    image: wefourweb/fibonacci:latest
    depends_on: 
      - redis-cache
    command: /root/app
    ports:
      - 8000:8000
      - 9000:9000
    env_file: 
      - .env